### ISSUE TITLE
addition of pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [Algo-Phantoms/Algo-Phantoms-Backend#13]
there is no pull request template to explain about pr and the set of checklists that it follows so would like to add one please assign it to me under gssoc'21

**Comment by diyajaiswal11** [comment]
Sure @Sloth-Panda , Go ahead.

**Comment by Sloth-Panda** [comment]
@diyajaiswal11 can you please add "level0/ level1/ level2/ level3" any of the tags to the issue and pr along with "gssoc21"as per gssoc guidelines
else they wont be counted . I think the way you have tagged gssoc wont count so please change that
