### ISSUE TITLE
Code Hierarchy of better understanding

### ISSUE THREAD

**Issue by PandeySomya77** [Algo-Phantoms/Algo-Phantoms-Backend#15]
In readme file there should be a well defined hierarchy of code. Like how models are defined and other MVT architecture.

**Comment by PandeySomya77** [comment]
Can I work on this issue?

**Comment by bhavikabadjate901** [comment]
Can I work on this issue?

**Comment by PandeySomya77** [comment]
Hey I have updated the things. Please merge my PR
