### ISSUE TITLE
On migration it say:  ModuleNotFoundError: No module named 'AlgoPhantomBackend.local_settings'

### ISSUE THREAD

**Issue by Aditya201551** [Algo-Phantoms/Algo-Phantoms-Backend#18]
I have installed all dependencies and followed all the directed steps but on running: 'python manage.py makemigrations' it shows ModuleNotFoundError: No module named 'AlgoPhantomBackend.local_settings'

ScreenShot is below:
![Screenshot (38)](https://user-images.githubusercontent.com/32588231/110841092-81a55480-82cb-11eb-9d54-107086069d64.png)

**Comment by Aditya201551** [comment]
On further reading and debugging the code I found that `local_settings` was never added to the file so Django cannot import it and also I found that the setting has many undefined variables and other migrations and minor issues that are not allowing the database to migrate and server to run, I have solved the issue and the app is up and running now(locally port:8000)

The screen shot is below: 

![Screenshot (39)](https://user-images.githubusercontent.com/32588231/110844170-18274500-82cf-11eb-9f8c-ec1f83c3bc2b.png)
.

It would be great if you assigned me the task to configure the settings file I will send a PR as soon as possible

ThankYou!(GSSOC 2021 participant)

**Comment by diyajaiswal11** [comment]
Hey @Aditya201551 , thank you for raising the issue. The purpose of defining the local_settings.py was that it contained the EMAIL_HOST_USER and EMAIL_HOST_PASSWORD. So inorder to have email verification while signing up, you need to define both of these in local_settings.py. So currently, this file was not pushed as it had credentials. Other PR has commented these lines and it will not cause any issue then.
