### ISSUE TITLE
Create model database for user score

### ISSUE THREAD

**Issue by Shagunjain10** [Algo-Phantoms/Algo-Phantoms-Backend#22]
When a user plays quizzes, we need to store their performance, marks, etc. So that users can see their progress.

**Comment by Shagunjain10** [comment]
can you please assign it to me? I am a gssoc participant.

**Comment by Naman-12911** [comment]
Hello I want to solve this issue please assign me under GSSOC.

**Comment by Malvika18** [comment]
can i work on this issue
