### ISSUE TITLE
Will like to update the tech stack section with their logo 

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Phantoms-Backend#23]
I will like to  add the logos of tech stack section used in this project this will make our read me file more attractive !!Will start work as soon as I get assigned !!

**Comment by diyajaiswal11** [comment]
Can you drop a screenshot of what it will exactly look like in README.md?

**Comment by rohank2502** [comment]
![Screenshot 2021-03-12 214501](https://user-images.githubusercontent.com/76584243/110967362-49aa1a00-837c-11eb-9159-ad5b1cb97aae.png)

**Comment by diyajaiswal11** [comment]
Sure @rohank2502 , Go ahead. But make sure you do the same for Django REST Framework.
