### ISSUE TITLE
Multiple Settings Modules

### ISSUE THREAD

**Issue by bhavikabadjate901** [Algo-Phantoms/Algo-Phantoms-Backend#28]
Usually, it’s a good idea to avoid multiple configuration files, instead, keep your project setup simple. But that’s not always possible, as a Django project starts to grow, the settings.py module can get fairly complex. In those cases, you also want to avoid using if statements like if not DEBUG: # do something.... For clarity and strict separation of what is development configuration and what is production configuration, you can break down the settings.py module into multiple files.

**Comment by bhavikabadjate901** [comment]
can you please assign it to me?
file structure will look like 

AlgoPhantomBackend/
 |-- AlgoPhantomBackend/
 |    |-- __init__.py
 |    |-- settings/
 |    |    |-- __init__.py
 |    |    |-- base.py
 |    |    |-- development.py
 |    |    |-- production.py
 |    |    +-- staging.py
 |    |-- urls.py
 |    +-- wsgi.py
 +-- manage.py

**Comment by diyajaiswal11** [comment]
> Usually, it’s a good idea to avoid multiple configuration files, instead, keep your project setup simple. But that’s not always possible, as a Django project starts to grow, the settings.py module can get fairly complex. In those cases, you also want to avoid using if statements like if not DEBUG: # do something.... For clarity and strict separation of what is development configuration and what is production configuration, you can break down the settings.py module into multiple files.

Hey @bhavikabadjate901 , I don't think this is a considerable issue, I would recommend you to go through the project and come up with more ideas and features to improvise the project. Happy learning :)
