### ISSUE TITLE
Add Pagination.py

### ISSUE THREAD

**Issue by hasanmdarif** [Algo-Phantoms/Algo-Phantoms-Backend#29]
Hey, I want to add pagination for quiz app. If you find it relevant, please assign me for this under gssoc21.
Thank you.
P.S: please check the attached file.
![Screenshot from 2021-03-14 11-26-34](https://user-images.githubusercontent.com/60822545/111058971-2dab9300-84b8-11eb-865a-3430e7717a35.png)

**Comment by harsh-9in** [comment]
@diyajaiswal11?

**Comment by harsh-9in** [comment]
@hasanmdarif 
assigned to you

**Comment by diyajaiswal11** [comment]
Hey @hasanmdarif , Please try to use _from rest_framework.pagination import PageNumberPagination_ as it is really easy to use and keeps the code clean. Let me know if you're stuck anywhere.

**Comment by hasanmdarif** [comment]
> Hey @hasanmdarif , Please try to use _from rest_framework.pagination import PageNumberPagination_ as it is really easy to use and keeps the code clean. Let me know if you're stuck anywhere.

Sure.  Please add relevant labels like gssoc21 and the level of problem

**Comment by Pushpit07** [comment]
Is this done or can I take it up? It's just 4-5 lines of code to be added

**Comment by harsh7in** [comment]
> Is this done or can I take it up? It's just 4-5 lines of code to be added

This is already done
