### ISSUE TITLE
[FEATURE] [GSSOC 2021] Adding user login and authentication with google: Login and Logout feature

### ISSUE THREAD

**Issue by Aditya201551** [Algo-Phantoms/Algo-Phantoms-Backend#33]
@diyajaiswal11 

I would like to add a feature for a user to **login/logout with their google account** and  also store their login credentials locally into their system till they logout manually(remember me feature)
In future updates, Facebook, Apple and GitHub login can also be added.

I would like to contribute to this feature so it would be great if the team assign me 

ThankYou(GSSOC 2021 participant )

**Comment by Naman-12911** [comment]
I want to solve this issue please assign me under GSSOC.

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11
> 
> I would like to add a feature for a user to **login/logout with their google account** and also store their login credentials locally into their system till they logout manually(remember me feature)
> In future updates, Facebook, Apple and GitHub login can also be added.
> 
> I would like to contribute to this feature so it would be great if the team assign me
> 
> ThankYou(GSSOC 2021 participant )

Sure @Aditya201551 , Go ahead.

**Comment by pallavi00021** [comment]
can I start working on this issue?? I'm gssoc'21 participant.   @diyajaiswal11
