### ISSUE TITLE
route.md file for getting idea of routes

### ISSUE THREAD

**Issue by harsh-9in** [Algo-Phantoms/Algo-Phantoms-Backend#35]
There should be a route.md file so that a new user who wants to use or contribute to the project can easily get the idea of every route and working/ purpose of that route.

**Comment by Pushpit07** [comment]
Can you assign this to me? I'll have a look at all urls.py files and collectively display information about all routes in a route.md file

**Comment by harsh-9in** [comment]
assigned to @Pushpit07
