### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Akash20x** [Algo-Phantoms/Algo-Phantoms-Backend#6]
I want to add issue templates for proposal, feature and documentation types so that there is proper way to create a new issue in your repo.

Please assign me this task as a part of GSSoC'21
and add necessary labels.

**Comment by diyajaiswal11** [comment]
Sure @Akash20x , Go ahead.

**Comment by Akash20x** [comment]
Please add necessary labels GSSoC'21, good first issue

**Comment by Akash20x** [comment]
I will send pull request when you add necessary labels on this issue

**Comment by Akash20x** [comment]
I will send pull request when you add necessary labels on this issue

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Akash20x** [comment]
Please check my pull request
